name: Compile kernel
on:
  workflow_dispatch:
jobs:
  Compile_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        shell: bash
        run: |
          #!/bin/bash
          apt install xmlstarlet
          wget "https://unraid-dl.sfo2.cdn.digitaloceanspaces.com/stable/unRAIDServer.plg"
          # Provide the XML file path as a command-line argument
          xml_file="unRAIDServer.plg"
          # Check if the XML file exists
          if [ ! -f "$xml_file" ]; then
            echo "XML file not found: $xml_file"
            exit 1
          fi
          # Use xmlstarlet to extract and assign entity values to variables
          while IFS= read -r entity; do
            entity_name="$(echo "$entity" | cut -d ' ' -f 1)"
            entity_value="$(echo "$entity" | cut -d ' ' -f 2-)"
            declare "entity_$entity_name=$entity_value"
          done < <(xmlstarlet sel -t -v "//*[starts-with(name(), '&')]" "$xml_file")
          # Output the variables
          echo "Entity variables:"
          compgen -A variable | grep '^entity_'
