name: Compile kernel
on:
  push:
    branches:
      - master
jobs:
  pull_and_edit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Test
        shell: bash
        run: |
          #!/bin/bash
          echo "Current working directory:"
          pwd
