name: Compile kernel
on:
  workflow_dispatch:
jobs:
  pull_and_edit:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          #!/bin/bash
          KERNEL_VERSION="6.1.49"
          major_version="6"
          UNRAID_VERSION="6.12.4"
          sudo apt -y install make gcc bison libelf-dev
          rm -dr /unraid
          mkdir -p unraid
          cd unraid
          wget -nvc https://mirrors.edge.kernel.org/pub/linux/kernel/v$major_version.x/linux-$KERNEL_VERSION.tar.xz
          wget -nvc https://unraid-dl.sfo2.cdn.digitaloceanspaces.com/stable/unRAIDServer-$UNRAID_VERSION-x86_64.zip
          mkdir -p linux
          tar -xf linux-$KERNEL_VERSION.tar.xz -C linux --strip-components 1
          unzip unRAIDServer-$UNRAID_VERSION-x86_64.zip -dq unRAIDServer
          cd unRAIDServer
          unsquashfs -d patches bzfirmware src
          cd ..
          cp -r unRAIDServer/patches/src/linux-*-Unraid/. linux/
          cd linux
          find . -type f -iname '*.patch' -print0 | xargs -n1 -0 patch -p1 -i
          sed -i 's/# CONFIG_AUDIT is not set/CONFIG_AUDIT=y/' .config
          yes "" | make oldconfig > /dev/null
          yes "" | make -j$(nproc) bzImage > /dev/null
          yes "" | make -j$(nproc) > /dev/null
