name: Compile kernel
on:
  workflow_dispatch:
jobs:
  pull_and_edit:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: |
          #!/bin/bash
          echo "Current working directory:"
          pwd
