name: Compile kernel
on:
  workflow_dispatch:
jobs:
  Compile_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        shell: bash
        run: |
          #!/bin/bash
          wget "https://unraid-dl.sfo2.cdn.digitaloceanspaces.com/stable/unRAIDServer.plg"
          # Provide the XML file path as a command-line argument
          xml_file="unRAIDServer.plg"
          # Check if the XML file exists
          if [ ! -f "$xml_file" ]; then
            echo "XML file not found: $xml_file"
            exit 1
          fi
          KERNEL_VERSION=$(sed -n 's/<!ENTITY version\s*"\(.*\)">/\1/p' "$xml_file")
          MAJOR_VERSION="${KERNEL_VERSION%%.*}"
          UNRAID_VERSION=$(sed -n 's/<!ENTITY kernel\s*"\([0-9.]*\)-Unraid">/\1/p' "$xml_file")
          echo $KERNEL_VERSION
          echo $MAJOR_VERSION
          echo $UNRAID_VERSION
          echo "{KERNEL_VERSION}={sed -n 's/<!ENTITY version\s*"\(.*\)">/\1/p' "$xml_file"}" >> "$GITHUB_ENV"
          echo "{MAJOR_VERSION}={${number%%.*}}" >> "$GITHUB_ENV"
          echo "{UNRAID_VERSION}={sed -n 's/<!ENTITY kernel\s*"\([0-9.]*\)-Unraid">/\1/p' "$xml_file"}" >> "$GITHUB_ENV"
      - name: Setup environment
        shell: bash
        run: |
          #!/bin/bash
          echo "----------------------------------------[Kernel version: $KERNEL_VERSION]---------------------------------------------"
          echo "----------------------------------------[Kernel major version: $MAJOR_VERSION]----------------------------------------"
          echo "----------------------------------------[unRAID version: $UNRAID_VERSION]---------------------------------------------"
